general:
    bind_addr: 127.0.0.1
    bind_port: 60022
    session_timeout: 180
    daemonize: true
    max_sessions_count: 200 # the maximum number of sessions 

logger:
    type: fh    # fh or syslog
    fh:
        level: info  # info, debug, warn, error
        file: /var/log/mymeeting/mymeeting.log

pbx:
    name: asterisk  # asterisk or freeswitch

    asterisk_connect_params:
        host: '127.0.0.1'
        port:
        auth_data:
            user:
            pass:

    freeswitch_connect_params:
        host: '127.0.0.1'
        port: 8021
        auth_data:
            pass: test
