general:
    bind_addr: 127.0.0.1
    bind_port: 60022
    session_timeout: 180
    daemonize: true
    logger:
        type: fh    # fh or syslog
        fh:
            level: info  # info, debug, warn, error
            file: /var/log/mymeeting/mymeeting.log

pbx:
    host: 127.0.0.1
    port: 8021
    pass: test
